Navbar logic
FACN3/parkapp pull request #28
Opened 2018-02-13 10:43 UTC by idantb101

Creating logic for the navbar, and deleting unnecessary files.

2018-02-13 16:01 UTC, sophiavocado approved these changes

2018-02-13 17:28 UTC, sophiavocado requested changes

2018-02-13 17:28 UTC, sophieeejw commented on src/components/Navbar.js
> +            this.state.isSeeMoreNav === true
which event triggers the change of the state for isSeeMoreNav?? 🤔

2018-02-14 08:27 UTC, idantb101 commented on src/components/Navbar.js
> +            this.state.isSeeMoreNav === true
the is no event that triggers the change yet, when there will be more pages then we will add the event.

2018-02-14 08:54 UTC, sophiavocado approved these changes

2018-02-14 08:54 UTC, sophieeejw commented on src/components/Navbar.js
> +            this.state.isSeeMoreNav === true
alright!

2018-02-14 09:17 UTC, merged